# Generated by Django 3.2.4 on 2021-07-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_auto_20210713_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
